# Generated by Django 2.1.15 on 2021-03-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20210308_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightstatechangeinformation',
            name='light',
        ),
        migrations.RemoveField(
            model_name='roomstatechangeinformation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='thermostatstatechangeinformation',
            name='thermostat',
        ),
        migrations.DeleteModel(
            name='LightStateChangeInformation',
        ),
        migrations.DeleteModel(
            name='RoomStateChangeInformation',
        ),
        migrations.DeleteModel(
            name='ThermostatStateChangeInformation',
        ),
    ]
