# Generated by Django 2.1.15 on 2021-03-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_auto_20210308_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='light',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='light',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='updated_at',
        ),
    ]
